blank_issues_enabled: false
contact_links:
  - name: Telegram Channel
    url: https://t.me/Netch
    about: Telegram Channel
  - name: Telegram Group
    url: https://t.me/Netch_Discuss_Group
    about: Telegram Group